#!/usr/bin/env bash
# record_cluster_facts.sh > config/sge/cluster.yaml
#
# Capture the SGE facts that check_sge_profile.py needs but cannot obtain from an
# ordinary submit host, because `qconf -sc`, `qconf -spl` and `qconf -sq` are
# permitted only from an ADMIN HOST.
#
# Run this ON AN ADMIN HOST (`qconf -sh` lists them; node519 works) and commit the
# result. The checker uses it as a fallback when qconf is denied, and cross-checks
# it against qconf when qconf answers, so a stale file is reported as drift rather
# than believed.
set -euo pipefail

if ! qconf -spl >/dev/null 2>&1; then
  echo "qconf is denied from $(hostname). Run this on an admin host (qconf -sh)." >&2
  exit 1
fi

queues=$(qstat -g c | awk 'NR>2 && $1 ~ /\.q$/ {print $1}')

printf '# Recorded facts about the SGE cluster.\n'
printf '# Generated by config/sge/record_cluster_facts.sh -- do not hand-edit.\n#\n'
printf '# qconf -sc / -spl / -sq are admin-host only; from a submit host they fail with\n'
printf '#     denied: host "..." is not an admin host\n'
printf '# which says nothing about whether a queue or complex exists. check_sge_profile.py\n'
printf '# falls back to these values, and warns if qconf later contradicts them.\n\n'
printf 'recorded_on: "%s"\n' "$(date +%Y-%m-%d)"
printf 'recorded_from: "%s"\n' "$(hostname -s)"
printf 'recorded_by: "config/sge/record_cluster_facts.sh"\n\n'

printf 'parallel_environments: [%s]\n\n' \
  "$(qconf -spl | sed 's/^/"/;s/$/"/' | paste -sd, -)"

printf 'complexes:\n'
printf '  # consumable: per_slot  -> qconf said YES; consumed once per slot\n'
printf '  # consumable: per_job   -> qconf said JOB; request the job total unchanged\n'
printf '  # consumable: false     -> qconf said NO;  requesting it RESERVES NOTHING\n'
qconf -sc | awk '
  !/^#/ && NF >= 6 && $3 == "MEMORY" {
    req = ($5 == "YES") ? "true" : "false"
    cons = ($6 == "YES") ? "per_slot" : ($6 == "JOB" ? "per_job" : "false")
    printf "  %s:\n    requestable: %s\n    consumable: %s\n", $1, req, cons
  }'

printf '\nqueues:\n'
for q in $queues; do
  hrt=$(qconf -sq "$q" 2>/dev/null | awk '/^h_rt/ {print $2; exit}')
  slots=$(qstat -g c | awk -v q="$q" '$1 == q {print $6; exit}')
  printf '  %s:\n' "$q"
  [ -n "${hrt:-}" ] && [ "$hrt" != "INFINITY" ] && printf '    h_rt: "%s"\n' "$hrt"
  [ -n "${slots:-}" ] && printf '    slots: %s\n' "$slots"
done
